from enum import IntEnum
from enum import unique


@unique
class CalculationType(IntEnum):
    BOUNDARY_NODE = -1
    EMBEDDED = 0
    STANDALONE = 1
    CONNECTED = 2
    BROAD_CRESTED = 3  # only orifices + weirs, corresponds
    SHORT_CRESTED = 4  # only orifices + weirs
    DOUBLE_CONNECTED = 5


@unique
class NodeType(IntEnum):
    NODE_2D_OPEN_WATER = 1
    NODE_2D_GROUNDWATER = 2
    NODE_1D_NO_STORAGE = 3
    NODE_1D_STORAGE = 4
    NODE_2D_BOUNDARIES = 5
    NODE_2D_GROUNDWATER_BOUNDARIES = 6
    NODE_1D_BOUNDARIES = 7


@unique
class LineType(IntEnum):
    LINE_1D_EMBEDDED = 0
    LINE_1D_ISOLATED = 1
    LINE_1D_CONNECTED = 2
    LINE_1D_LONG_CRESTED = 3
    LINE_1D_SHORT_CRESTED = 4
    LINE_1D_DOUBLE_CONNECTED = 5
    LINE_1D2D_SINGLE_CONNECTED_WITH_STORAGE = 51
    LINE_1D2D_SINGLE_CONNECTED_WITHOUT_STORAGE = 52
    LINE_1D2D_DOUBLE_CONNECTED_WITH_STORAGE = 53
    LINE_1D2D_DOUBLE_CONNECTED_WITHOUT_STORAGE = 54
    LINE_1D2D_POSSIBLE_BREACH = 55
    LINE_1D2D_ACTIVE_BREACH = 56
    LINE_1D2D_GROUNDWATER_57 = 57
    LINE_1D2D_GROUNDWATER_58 = 58  # diff to 57?
    LINE_2D = 100
    LINE_2D_OBSTACLE = 101  # levee
    LINE_2D_VERTICAL = 150
    LINE_2D_GROUNDWATER = -150
    LINE_2D_BOUNDARY_200 = 200
    LINE_2D_BOUNDARY_300 = 300
    LINE_2D_BOUNDARY_400 = 400
    LINE_2D_BOUNDARY_500 = 500


@unique
class ContentType(IntEnum):
    TYPE_V2_PIPE = 1
    TYPE_V2_CHANNEL = 2
    TYPE_V2_CULVERT = 3
    TYPE_V2_ORIFICE = 4
    TYPE_V2_WEIR = 5
    TYPE_V2_MANHOLE = 6
    TYPE_V2_PUMPSTATION = 7
    TYPE_V2_LEVEE = 8
    TYPE_V2_1D_LATERAL = 9
    TYPE_V2_1D_BOUNDARY_CONDITIONS = 10
    TYPE_V2_2D_BOUNDARY_CONDITIONS = 11
    TYPE_V2_CONNECTION_NODES = 12
    TYPE_V2_BREACH = 13
    TYPE_V2_CROSS_SECTION_DEF = 14
    TYPE_V2_CROSS_SECTION_LOCATION = 15
    TYPE_V2_ADDED_CALCULATION_POINT = 16
    TYPE_V2_WINDSHIELD = 17


@unique
class FrictionType(IntEnum):
    CHEZY = 1
    MANNING = 2


@unique
class CrossSectionShape(IntEnum):
    # TODO Check valus, 0 possibly means "CLOSED_RECTANGLE"
    RECTANGLE = 1
    CIRCLE = 2
    EGG = 3
    TABULATED_RECTANGLE = 5
    TABULATED_TRAPEZIUM = 6
