version: '3.5'

services:
  threedigrid-builder:
    image: threedigrid-builder:dev
    build:
      context: .
      target: build
      dockerfile: Dockerfile
    ports: 
      - 8888:8888
    volumes:
      - vscode-extenstions:/root/.vscode-server/extensions
      - ../models:/models
      - ./:/threedigrid-builder
      - /mnt/d/tmp:/mnt/d/tmp
    working_dir: /threedigrid-builder
    command: ["/usr/local/bin/python3", "/usr/local/bin/jupyter", "lab", 
                "--port=8888", "--ip=0.0.0.0", "--allow-root", "--no-browser"]
    privileged: true
      
volumes:
  vscode-extenstions:
