name: Release

on:
  push:
    tags:
      - '*'
  pull_request:  # also build on PRs touching this file
    paths:
      - ".github/workflows/build_wheels.yml"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.3.0
        # to supply options, put them in 'env', like:
        env:
          CIBW_SKIP: "pp* *musllinux*" # skips pypy and musllinux
          CIBW_ARCHS: auto64  # only 64-bit (convincing CMAKE of 32-bit is a TODO)
          CIBW_ENVIRONMENT_MACOS:
            FC=gfortran-9
            LDFLAGS=-Wl,-rpath,${{ github.workspace }}/libthreedigrid/lib
          CIBW_ENVIRONMENT_LINUX:
            LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/project/libthreedigrid/lib/
          # Before creating the wheel, we build libthreedigrid (fortran) and copy the libraries
          # into /usr/local/bin
          CIBW_BEFORE_ALL: |
            pip install cmake &&
            ./build.sh &&
            cat WHEEL_LICENSE_POSIX >> LICENSE
          CIBW_BEFORE_ALL_WINDOWS: build.cmd && cat WHEEL_LICENSE_WINDOWS >> LICENSE
          CIBW_BEFORE_BUILD_WINDOWS: pip install delvewheel
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: >-
            delvewheel repair -w {dest_dir}
            --add-path ${{ github.workspace }}\libthreedigrid\bin
            --no-mangle "libwinpthread-1.dll" {wheel}

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
          retention-days: 5

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    # Extra protection in case this github action is triggered on a PR (e.g. when
    # debugging the wheelbuilder. Only upload to PyPI on an actual tag.
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
