name: Release

on:
  push:
    tags:
      - '*'
  pull_request:  # also build on PRs touching this file
    paths:
      - ".github/workflows/build_wheels.yml"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0
        # to supply options, put them in 'env', like:
        env:
          CIBW_SKIP: "pp* *-win32"  # skips pypy, 32-bit windows
          CIBW_ENVIRONMENT_MACOS:
            FC=gfortran-9
            DYLD_FALLBACK_LIBRARY_PATH=/project/libthreedigrid/lib/
            LDFLAGS=-Wl,-rpath,${{ github.workspace }}/libthreedigrid/lib
          CIBW_ENVIRONMENT_LINUX:
            LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/project/libthreedigrid/lib/
          # Before creating the wheel, we build libthreedigrid (fortran) and copy the libraries
          # into /usr/local/bin
          CIBW_BEFORE_ALL: |
            pip install cmake &&
            ./build.sh &&
            cat WHEEL_LICENSE_LINUX >> LICENSE
          CIBW_BEFORE_ALL_WINDOWS: build.cmd && cat WHEEL_LICENSE_WINDOWS >> LICENSE
          CIBW_BEFORE_BUILD_WINDOWS: pip install delvewheel
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: delvewheel repair --add-path ${{ github.workspace }}\libthreedigrid\bin -w {dest_dir} {wheel}
          # The tests can't be done always as some dependencies (rasterio, pyproj)
          # cannot be installed inside the manylinux1 docker.
          CIBW_TEST_EXTRAS: test,gridadmin
          CIBW_TEST_COMMAND: pytest --pyargs threedigrid_builder.tests

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
          retention-days: 5

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    # Extra protection in case this github action is triggered on a PR (e.g. when
    # debugging the wheelbuilder. Only upload to PyPI on an actual tag.
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
