name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04] # , windows-2019, macos-10.15]

    steps:
      - uses: actions/checkout@v2

      - name: Install Visual C++ for Python 2.7
        if: runner.os == 'Windows'
        run: choco install vcpython27 -f -y

      - name: Build wheels
        uses: joerick/cibuildwheel@v1.10.0
        # to supply options, put them in 'env', like:
        env:
          CIBW_SKIP: pp*  # skips pypy
          CIBW_ARCHS: auto64  # only 64-bit
          # Use the oldest manylinux docker (with fortran compiler version GNU 4.8.2)
          # So that libquadmath and libz are not dynamically linked.
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux1
          CIBW_MANYLINUX_I686_IMAGE: manylinux1  # 32-bit currently not used
          # Before creating the wheel, we build libthreedigrid (fortran) and copy the libraries
          # into /usr/local/bin
          CIBW_BEFORE_ALL: |
            pip install cmake &&
            ./full_build.sh &&
            cp -rv /project/libthreedigrid/lib/libthreedigrid*.so* /usr/local/lib/ &&
            cat WHEEL_LICENSE_LINUX >> LICENSE
          # The tests require extra requirements (see extras_require in setup.py)
          CIBW_TEST_EXTRAS: test,gridadmin
          # The pytest command has two custom things:
          # - --import-mode=importlib so that pytest does not mess up the PATH.
          #   If you do not do that, the (uncompiled) contents of
          #   {package}/threedigrid_builder will be tested against instead of the
          #   installed contents of the wheel that was built.
          # - We skip tests marked with 'spatialite' because we do not have the spatialite
          #   extension installed inside the manylinux docker.
          CIBW_TEST_COMMAND: "pytest --import-mode=importlib -m 'not spatialite' {package}/threedigrid_builder/tests"

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
          retention-days: 5
