name: Lint

on:
  push:
    branches:
      - master
      - fixes_*
    tags:
      - '*'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run black, flake8, isort
        uses: pre-commit/action@v2.0.0
