name: Linux

# Run on PR requests. And on master itself.
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  TestLinux:
    name: Python ${{ matrix.python }} ${{ matrix.display_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Python 3.10
          - python: '3.10'
            os: ubuntu-22.04
            numpy: numpy==1.26.*
            display_name: "numpy 1.26"
          - python: '3.10'
            os: ubuntu-22.04
            numpy: numpy==2.2.*
            display_name: "numpy 2.2"
          # Python 3.11
          - python: '3.11'
            os: ubuntu-22.04
            numpy: numpy==1.26.*
            display_name: "numpy 1.26"
          - python: '3.11'
            os: ubuntu-22.04
            numpy: numpy==2.*
            display_name: "numpy 2"
          # Python 3.12
          - python: '3.12'
            os: ubuntu-22.04
            numpy: numpy==1.26.*
            display_name: "numpy 1.26"
          - python: '3.12'
            os: ubuntu-22.04
            numpy: numpy==2.*
            display_name: "numpy 2"
          # Python 3.13
          - python: '3.13'
            os: ubuntu-24.04
            setuptools: setuptools>=69.*
            numpy: numpy==2.*
            display_name: "numpy 2"

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install GDAL, sqlite3 and spatialite
        run: |
          sudo apt-get update && sudo apt-get install --yes --no-install-recommends libgdal-dev sqlite3 libsqlite3-mod-spatialite

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python }}-${{ matrix.numpy }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python }}-${{ matrix.numpy }}

      - name: Install python dependencies
        shell: bash
        run: |
          pip install --upgrade pip wheel scikit-build-core setuptools ${{ matrix.numpy }}
          pip install .[test,gridadmin] -v --no-cache-dir --no-build-isolation "GDAL==$(gdal-config --version)"          
          pip list

      - name: Run unittests
        shell: bash
        run: |
          pytest

      - name: Run integration tests
        shell: bash
        run: |
          pytest integration_tests
