name: Linux

# Run on PR requests. And on master itself.
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  TestLinux:
    name: Python ${{ matrix.python }} ${{ matrix.display_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - python: '3.10'
            os: ubuntu-22.04
          - python: '3.11'
            os: ubuntu-22.04
          - python: '3.11'
            os: ubuntu-22.04
          - python: '3.12'
            os: ubuntu-22.04
          - python: '3.12'
            os: ubuntu-22.04
          - python: '3.13'
            os: ubuntu-24.04
          - python: '3.14'
            os: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install GDAL, sqlite3 and spatialite
        run: |
          sudo apt-get update && sudo apt-get install --yes --no-install-recommends libgdal-dev sqlite3 libsqlite3-mod-spatialite

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python }}

      - name: Install python dependencies
        shell: bash
        run: |
          pip install --upgrade pip wheel scikit-build-core setuptools
          pip install .[test,gridadmin] --no-build-isolation --no-cache-dir --force-reinstall GDAL==$(gdal-config --version) 
          pip list

      - name: Run unittests
        shell: bash
        run: |
          pytest

      - name: Run integration tests
        shell: bash
        run: |
          pytest integration_tests
