name: Release

on:
  push:
    tags:
      - '*'
  pull_request:  # also build on PRs touching this file
    paths:
      - ".github/workflows/build_wheels.yml"

jobs:
  build_wheels:
    name: Build wheels on testbank
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2

      - name: Build wheels
        uses: joerick/cibuildwheel@v2.1.3
        env:
          CIBW_PLATFORM: "linux"
          CIBW_BUILD: "cp37-manylinux_x86_64"  # matches calccore python version
          CIBW_ENVIRONMENT_LINUX:
            LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/project/libthreedigrid/lib/
          # Before creating the wheel, we build libthreedigrid (fortran) and copy the libraries
          # into /usr/local/bin
          CIBW_BEFORE_ALL: |
            pip install cmake &&
            ./build.sh &&
            cat WHEEL_LICENSE_POSIX >> LICENSE
          CIBW_TEST_EXTRAS: test,gridadmin
          CIBW_TEST_COMMAND: pytest --pyargs threedigrid_builder.tests

      - name: Move wheels
        run: mv ./wheelhouse/*.whl /var/wheels

  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    # Extra protection in case this github action is triggered on a PR (e.g. when
    # debugging the wheelbuilder. Only upload to PyPI on an actual tag.
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_token }}
